ISP_FW_VER=1.1.6

COMPILER_VER=540

SRCS := $(DIR)/tx-isp-debug.c \
	$(DIR)/tx-isp-module.c

ifdef SENSOR_REGISTRY_IN_SDK
    SRCS += common/isp/common/tx-isp-sinfo.c
endif

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += sdk/$(SOC_FAMILY)/lib$(SOC_FAMILY)-firmware-$(ISP_FW_VER)-$(COMPILER_VER)-31014.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
