ISP_FW_VER=1.2.0

ldflags-y += --no-warn-mismatch

SRCS := $(DIR)/tx-isp-funcs.c \
	$(DIR)/tx-isp-module.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(KERNEL_VERSION)/sdk/$(SOC_FAMILY)/$(ISP_FW_VER)/lib$(SOC_FAMILY)-firmware.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
