MODULE_NAME := sensor_imx225_$(SOC_FAMILY)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC_FAMILY)

SRCS := $(DIR)/imx225/imx225.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
