ISP_FW_VER=1.3.1

SRCS := $(DIR)/tx-isp-funcs.c \
	$(DIR)/tx-isp-module.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += sdk/$(SOC_FAMILY)/lib$(SOC_FAMILY)-firmware-$(ISP_FW_VER).a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
