MODULE_NAME := sensor_sc1245a_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/sc1245a/sc1245a.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
