MODULE_NAME := tx-isp-$(SOC_FAMILY)
OUT := $(MODULE_NAME)

DIR=isp/$(SOC_FAMILY)

SRCS := \
  $(DIR)/tx-isp-debug.c \
  $(DIR)/tx-isp-module.c \
  $(DIR)/txx-funcs.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/libt21-firmware.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
