MODULE_NAME := sensor_$(SENSOR_MODEL)_$(SOC_FAMILY)

OUT := $(MODULE_NAME)

DIR=4.4/sensor-src/$(SOC_FAMILY)

SRCS := \
    $(DIR)/$(SENSOR_MODEL).c \
    4.4/sensor-src/common/sensor-info.c

ccflags-y += -I$(src)/4.4/isp/include
ccflags-y += -I$(src)/4.4/sensor-src/include

OBJS := $(SRCS:%.c=%.o) \
	$(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
