MODULE_NAME := sensor_sc2232h_t31
OUT := $(MODULE_NAME)

DIR=sensors/$(FAMILY)

SRCS := $(DIR)/sc2232h/sc2232h.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
