ISP_FW_VER=1.3.0
COMPILER_VER=540

SRCS := $(DIR)/tx-isp-debug.c \
	$(DIR)/tx-isp-module.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
ifdef CONFIG_MULTI_SENSOR
    OBJS += sdk/$(SOC_FAMILY)/lib$(SOC_FAMILY)-firmware-$(ISP_FW_VER)-$(COMPILER_VER)-31014-double.a
    ccflags-y += -DCONFIG_MULTI_SENSOR
else
    OBJS += sdk/$(SOC_FAMILY)/lib$(SOC_FAMILY)-firmware-$(ISP_FW_VER)-$(COMPILER_VER)-31014.a
endif

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
