MODULE_NAME := sensor_os05a10_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/os05a10/os05a10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
