MODULE_NAME := tx-isp-$(SOC)
OUT := $(MODULE_NAME)

DIR=isp/$(SOC)

SRCS := \
    $(DIR)/tx-isp-debug.o \
    $(DIR)/tx-isp-device.o \
    $(DIR)/tx-isp-frame-channel.o \
    $(DIR)/tx-isp-interrupt.o \
    $(DIR)/tx-isp-ldc.o \
    $(DIR)/tx-isp-mscaler.o \
    $(DIR)/tx-isp-ncu.o \
    $(DIR)/tx-isp-videobuf.o \
    $(DIR)/txx-funcs.o \
    $(DIR)/apical-isp/apical_calibrations.o \
    $(DIR)/apical-isp/apical_calibrations_init.o \
    $(DIR)/apical-isp/apical_custom_initialization.o \
    $(DIR)/apical-isp/apical_dynamic_calibrations.o \
    $(DIR)/apical-isp/apical_isp_io.o \
    $(DIR)/apical-isp/apical_static_calibrations.o \
    $(DIR)/apical-isp/ApicalDefault.o \
    $(DIR)/apical-isp/log.o \
    $(DIR)/apical-isp/sensor_drv.o \
    $(DIR)/apical-isp/system_chardev.o \
    $(DIR)/apical-isp/system_i2c.o \
    $(DIR)/apical-isp/system_io.o \
    $(DIR)/apical-isp/system_isp_io.o \
    $(DIR)/apical-isp/system_semaphore.o \
    $(DIR)/apical-isp/system_spi.o \
    $(DIR)/apical-isp/system_timer.o \
    $(DIR)/apical-isp/system_uart.o \
    $(DIR)/apical-isp/tx-isp-core.o \
    $(DIR)/apical-isp/tx-isp-core-tuning.o \
    $(DIR)/apical-isp/tx-isp-load-parameters.o \
    $(DIR)/videoin/tx-isp-vic.o \
    $(DIR)/videoin/tx-isp-sci.o \
    $(DIR)/videoin/tx-isp-video-in.o

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/apical-isp/libapical_isp.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
