ccflags-y += -I$(src)/common/sensor-src/include
# Single-kernel sensor dirs live in common/; t31/t40/t41/t41zrt are still
# kept per kernel (different calling conventions), so they stay under the tree.
ifneq ($(filter $(SOC_FAMILY),t31 t40 t41 t41zrt),)
DIR := $(KERNEL_VERSION)/sensor-src/$(SOC_FAMILY)
else
DIR := common/sensor-src/$(SOC_FAMILY)
endif

ifneq ($(SENSOR_MODEL),)
	MODULE_NAME := sensor_$(SENSOR_MODEL)_$(SOC_FAMILY)
	OUT := $(MODULE_NAME)
	SRCS := \
		$(DIR)/$(SENSOR_MODEL).c \
		common/sensor-src/common/sensor-info.c
	OBJS := $(SRCS:%.c=%.o) \
		$(ASM_SRCS:%.S=%.o)
	$(OUT)-objs := $(OBJS)
	obj-m += $(OUT).o
	CFLAGS_$(SENSOR_MODEL).o := -DKBUILD_MODNAME=\"$(MODULE_NAME)\"
endif

# Build additional sensor modules if defined
ifneq ($(SENSOR_1_MODEL),)
	MODULE_1_NAME := sensor_$(SENSOR_1_MODEL)_$(SOC_FAMILY)
	OUT_1 := $(MODULE_1_NAME)
	SRCS_1 := \
		$(DIR)/$(SENSOR_1_MODEL).c \
		common/sensor-src/common/sensor-info.c
	OBJS_1 := $(SRCS_1:%.c=%.o) \
			$(ASM_SRCS:%.S=%.o)
	$(OUT_1)-objs := $(OBJS_1)
	obj-m += $(OUT_1).o
	CFLAGS_$(SENSOR_1_MODEL).o := -DKBUILD_MODNAME=\"$(MODULE_1_NAME)\"
endif

ifneq ($(SENSOR_2_MODEL),)
	MODULE_2_NAME := sensor_$(SENSOR_2_MODEL)_$(SOC_FAMILY)
	OUT_2 := $(MODULE_2_NAME)
	SRCS_2 := \
		$(DIR)/$(SENSOR_2_MODEL).c \
		common/sensor-src/common/sensor-info.c
	OBJS_2 := $(SRCS_2:%.c=%.o) \
			$(ASM_SRCS:%.S=%.o)
	$(OUT_2)-objs := $(OBJS_2)
	obj-m += $(OUT_2).o
	CFLAGS_$(SENSOR_2_MODEL).o := -DKBUILD_MODNAME=\"$(MODULE_2_NAME)\"
endif
