
MODULE_NAME := sensor_sc200ai_t31
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/sc200ai/sc200ai.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

