MODULE_NAME := sensor_ov2735b_$(SOC)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/ov2735b/ov2735b.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
