ifeq ($(FAMILY),)
  @echo FAMILY must be set
endif

ccflags-y := -DRELEASE -DUSER_BIT_32 -DKERNEL_BIT_32 -Wno-date-time -D_GNU_SOURCE
ccflags-y += -I$(src)/isp/$(FAMILY)/include

include $(src)/sinfo/Kbuild
include $(src)/gpio/Kbuild
include $(src)/audio/$(FAMILY)/oss2/Kbuild
include $(src)/avpu/$(FAMILY)/Kbuild
include $(src)/isp/$(FAMILY)/Kbuild
include $(src)/sensors/$(FAMILY)/gc2053/Kbuild
include $(src)/sensors/$(FAMILY)/gc2083/Kbuild
include $(src)/sensors/$(FAMILY)/gc4653/Kbuild
include $(src)/sensors/$(FAMILY)/imx307/Kbuild
include $(src)/sensors/$(FAMILY)/jxf37/Kbuild
include $(src)/sensors/$(FAMILY)/jxh62/Kbuild
include $(src)/sensors/$(FAMILY)/jxq03/Kbuild
include $(src)/sensors/$(FAMILY)/jxq03p/Kbuild
include $(src)/sensors/$(FAMILY)/sc200ai/Kbuild
include $(src)/sensors/$(FAMILY)/sc2232h/Kbuild
include $(src)/sensors/$(FAMILY)/sc2335/Kbuild
include $(src)/sensors/$(FAMILY)/sc3338/Kbuild
include $(src)/sensors/$(FAMILY)/sc5235/Kbuild
