MODULE_NAME := audio
OUT := $(MODULE_NAME)

DIR=common/audio/t23/oss3

SRCS := \
  $(DIR)/audio_dsp.c \
  $(DIR)/audio_debug.c \
  $(DIR)/host/audio_aic.c \
  $(DIR)/inner_codecs/codec.c \
  $(DIR)/board/t23_platform.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
