MODULE_NAME := mpsys_driver
OUT := $(MODULE_NAME)

DIR := common/misc/mpsys-driver

SRCS := $(DIR)/mpsys_module.c \
	$(DIR)/private-funcs.c

# Firmware blob is selected per kernel version
ifeq ($(KERNEL_VERSION),3.10.14)
	KVERSION := 31014
else
	KVERSION := 4494
endif

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += sdk/$(SOC_FAMILY)/lib$(SOC_FAMILY)-mpsys-firmware-720-$(KVERSION).a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
