MODULE_NAME := mpsys_driver
OUT := $(MODULE_NAME)

DIR := common/misc/mpsys-driver

SRCS := $(DIR)/mpsys_module.c \
	$(DIR)/private-funcs.c

# Firmware blob is selected per kernel version
ifeq ($(KERNEL_VERSION),3.10.14)
	KVERSION := 3-10-14
else
	KVERSION := 4-4-94
endif

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(DIR)/$(SOC_FAMILY)-libmpsys-firmware-$(KVERSION).a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
