MODULE_NAME := sensor_$(SENSOR_MODEL)_$(SOC_FAMILY)

OUT := $(MODULE_NAME)

DIR=$(KERNEL_VERSION)/sensor-src/$(SOC_FAMILY)

SRCS := \
    $(DIR)/$(SENSOR_MODEL).c \
    $(KERNEL_VERSION)/sensor-src/common/sensor-info.c

ccflags-y += -I$(src)/$(KERNEL_VERSION)/isp/include
ccflags-y += -I$(src)/$(KERNEL_VERSION)/sensor-src/include

OBJS := $(SRCS:%.c=%.o) \
	$(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
