MODULE_NAME := sensor_$(SENSOR_MODEL)_$(SOC_FAMILY)
OUT := $(MODULE_NAME)

DIR=3.10/sensor-src/$(SOC_FAMILY)

SRCS := $(DIR)/$(SENSOR_MODEL).c 3.10/sensor-src/common/sensor-info.c

ccflags-y += -I$(src)/3.10/sensor-src/include

OBJS := $(SRCS:%.c=%.o) \
	$(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
