MODULE_NAME := sensor_jxk06_$(SOC_FAMILY)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC_FAMILY)

SRCS := $(DIR)/jxk06/jxk06.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
