MODULE_NAME := sensor_jxf23-s0_t40
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/jxf23-s0/jxf23-s0.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
