# Match the factory module name
MODULE_NAME := gpio-keys
OUT := $(MODULE_NAME)

DIR=$(KERNEL_VERSION)/misc/gpio-keys

SRCS := \
  $(DIR)/gpio-key.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

