include $(src)/sensors/$(SOC)/gc2053
include $(src)/sensors/$(SOC)/gc2053-double
include $(src)/sensors/$(SOC)/imx327
include $(src)/sensors/$(SOC)/jxf23
include $(src)/sensors/$(SOC)/sc200ai
include $(src)/sensors/$(SOC)/sc2310
include $(src)/sensors/$(SOC)/sc2331
include $(src)/sensors/$(SOC)/sc301IoT
