FW_VER=1.6.2

MODULE_NAME := vdec_module
OUT := $(MODULE_NAME)

DIR=common/video/a1/vdec

ccflags-y += -I$(src)/$(DIR)/include

SRCS := $(DIR)/vdec-module.c \
	$(DIR)/vdec-funcs.c


OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += sdk/$(SOC_FAMILY)/libvdec-firmware-$(FW_VER)-720-4494.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
