ISP_FW_VER=1.0.33

SRCS := $(DIR)/tx-isp-debug.c \
	$(DIR)/tx-isp-module.c \
	$(DIR)/txx-funcs.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += sdk/$(SOC_FAMILY)/lib$(SOC_FAMILY)-firmware-$(ISP_FW_VER).a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
