MODULE_NAME := hdmi_audio
OUT := $(MODULE_NAME)

DIR=common/audio/a1/hdmi_audio

ccflags-y += -I$(src)/$(DIR)/include

SRCS := $(DIR)/hdmi_dsp.c \
	$(DIR)/hdmi_audio_debug.c


OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
