# Match the factory module name
MODULE_NAME := motor
OUT := $(MODULE_NAME)

DIR=misc/motor

SRCS := \
  $(DIR)/motor.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

