MODULE_NAME := audio
OUT := $(MODULE_NAME)

DIR=$(KERNEL_VERSION)/$(MODULE_NAME)/$(SOC_FAMILY)/oss3
ccflags-y += -I$(src)/$(DIR)/include

SRCS := \
  $(DIR)/audio_dsp.c \
  $(DIR)/audio_debug.c \
  $(DIR)/host/audio_aic.c \
  $(DIR)/inner_codecs/codec.c \
  $(DIR)/host/dmic/as-fmtcov/as-fmtcov.c \
  $(DIR)/host/dmic/as-dbus/as-dbus.o \
  $(DIR)/host/dmic/as-dma/as-dma.o \
  $(DIR)/host/dmic/as-dmic/as-dmic.o \
  $(DIR)/board/t41_platform.o

OBJS := $(SRCS:%.c=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
