SRCS := $(DIR)/tx-isp-debug.c \
	$(DIR)/tx-isp-module.c \
	$(DIR)/tx-isp-funcs.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(KERNEL_VERSION)/sdk/lib$(SOC_FAMILY)-firmware.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
