ISP_FW_VER=1.1.5.2
COMPILER_VER=540

SRCS := $(DIR)/tx-isp-debug.c \
	$(DIR)/tx-isp-module.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(KERNEL_VERSION)/sdk/$(SOC_FAMILY)/$(ISP_FW_VER)/lib$(SOC_FAMILY)-firmware-$(COMPILER_VER).a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
