MODULE_NAME := sinfo
OUT := $(MODULE_NAME)

DIR=$(MODULE_NAME)

SRCS := $(KERNEL_VERSION)/misc/$(DIR)/sensor_info.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
