
MODULE_NAME := sensor_gc2053-double_t31
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC)

SRCS := $(DIR)/gc2053-double/gc2053-double.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o

