MODULE_NAME := audio
OUT := $(MODULE_NAME)

DIR := $(KERNEL_VERSION)/$(MODULE_NAME)/$(SOC_FAMILY)/oss3

ccflags-y += -I$(src)/include

SRCS := \
  $(DIR)/audio_dsp.c \
  $(DIR)/audio_debug.c \
  $(DIR)/host/audio_aic.c \
  $(DIR)/host/audio_dmic.c \
  $(DIR)/inner_codecs/codec.c \
  $(DIR)/boards/platform.c


OBJS := $(SRCS:%.c=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
