ISP_FW_VER=1.2.0

ldflags-y += --no-warn-mismatch

SRCS := $(DIR)/tx-isp-funcs.c \
	$(DIR)/tx-isp-module.c

# Determine the kernel version based on SOC type and KERNEL_VERSION
ifeq ($(SOC_FAMILY),t41)
	ifeq ($(KERNEL_VERSION),4.4)
		KVERSION := 4-4-94
	else
		KVERSION := 3-10-14
	endif
else ifeq ($(SOC_FAMILY),t40)
	KVERSION := 4-4-94
endif

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)
OBJS += $(KERNEL_VERSION)/sdk/$(SOC_FAMILY)/$(ISP_FW_VER)/lib$(SOC_FAMILY)-firmware.a

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
