MODULE_NAME := sensor_os03b10_$(SOC_FAMILY)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC_FAMILY)

SRCS := $(DIR)/os03b10/os03b10.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
