MODULE_NAME := sensor_sc1245_$(SOC_FAMILY)
OUT := $(MODULE_NAME)

DIR=sensors/$(SOC_FAMILY)

SRCS := $(DIR)/sc1245/sc1245.c

OBJS := $(SRCS:%.c=%.o) $(ASM_SRCS:%.S=%.o)

$(OUT)-objs := $(OBJS)

obj-m += $(OUT).o
